dist: xenial
sudo: required

language: python
python:
  - '3.6'
  - '3.7'

install: pip install tox-travis
script: tox

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1

stages:
  - lint
  - test
  - deploy

jobs:
  include:
    - { stage: lint, python: 3.6, env: TOXENV=flake8 }
    - { stage: lint, python: 3.6, env: TOXENV=pylint }
    - { stage: lint, python: 3.7, env: TOXENV=flake8 }
    - { stage: lint, python: 3.7, env: TOXENV=pylint }

    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        skip_cleanup: true
        user: Bashar.said
        password:
          secure:
